-- Schema for Oracle table
CREATE TABLE MESES (
  ANO_MES           VARCHAR2(7) PRIMARY KEY,
  ESTOQUE_INICIAL   NUMBER(18,3),
  PRODUCAO          NUMBER(18,3),
  VENDAS_QTD        NUMBER(18,3),
  FATURAMENTO       NUMBER(18,2),
  CUSTO_UNITARIO    NUMBER(18,2),
  CUSTO_MEDIO_ANT   NUMBER(18,2),
  CUSTO_MEDIO       NUMBER(18,2),
  ESTOQUE_FINAL     NUMBER(18,3),
  CMV               NUMBER(18,2),
  MARGEM_BRUTA      NUMBER(18,2),
  PRECO_MEDIO       NUMBER(18,2),
  CRIADO_EM         TIMESTAMP DEFAULT SYSTIMESTAMP
);
